#### Pipeline for preprocessing, aligning, calling, and filtering candidate L1HS insertions from HATseq libraries. ####

# Import required libraries
import pandas as pd
import os
import re
import gzip
import pysam
import numpy as np 
import math
import statistics
from snakemake.utils import validate

# Load helper functions
include: "rules/common.smk"

# Read config variables as constants
TE_NAME = config["te_name"]
REF_GENOME = config["bwa_ref_genome"]
REFERENCE_DIR = config["reference_dir"]
ERROR_PRONE = config.get("error_prone", "-NA-") # optional
TRUTH_SET = config.get("truth_set", "-NA-") # optional
LIBRARY = config["library"]
SEQ_PLATFORM = config['sequencing_platform']
SEQ_CENTER = config['sequencing_center']

# Read metadata
samples = pd.read_csv(config["metadata"], sep="\t", dtype=str)

# Validate configuration
config_schema = os.path.join(os.path.dirname(workflow.basedir), "config", "schemas", "config.schema.yml")
sample_schema = os.path.join(os.path.dirname(workflow.basedir), "config", "schemas", "samples.schema.yml")

validate(config, config_schema)
validate(samples, sample_schema)

# Format metadata
set_sample_names(samples)
samples = samples.set_index("sample_name", drop=False)

# Create reference file constants
EVRONY_KR = REFERENCE_DIR + "/RepeatMasker/hg38.Evrony_KR_960.v37.revised.bed" # Lifted over
REPEAT_MASKER = REFERENCE_DIR + "/RepeatMasker/hg38.repeatmasker.bed"
HOMOPOLYMERS = REFERENCE_DIR + "/human/hg38.hg19.homo8.chr.bed" # Lifted over
SEGDUPS = REFERENCE_DIR + "/SegDup/hg38.genomicSuperDups.v37.chr.bed"
HG38 = REFERENCE_DIR + "/human/hg38.genome"
L1HS_DECOY = REFERENCE_DIR + "/L1HS_decoy_sequence.fasta"
I1KGP = REFERENCE_DIR + "/1kgp/ALL_MELT_ME_1000G_HC_20190901.AF.bed"
GNOMAD = REFERENCE_DIR + "/gnomAD-SV/gnomad.v4.1.ME.sites.bed" 
XTEA = REFERENCE_DIR + "/xTea/xTea_Borges-Monroy2021.accessioned.bed"
NYUWA = REFERENCE_DIR + "/nyuwa/MEI.GRCh38.HMEIDv1.1.final.bed"
HGSVC3 = REFERENCE_DIR + "/HGSVC3/MEI_Callset_GRCh38.ALL.20241211.bed"
HGSVC3_MELT_LRA = REFERENCE_DIR + "/HGSVC3/Ortho_MEI_GRCh38.ALL.20241211.bed"
ONT1019 = REFERENCE_DIR + "/1019_ONT/1019_ONT_Schloissnig2025.bed"

localrules: HATseq

rule HATseq:
	input:
		expand([
		"{sample}/{sample}_mappable_R1_list.txt",
		"{sample}/{sample}_peak_sorted_bwa.bam",
		"{sample}/{sample}_Ntag_list.txt",
		"{sample}/{sample}_pass_gmotif_list.txt",
		"{sample}/{sample}_polyT_reads.txt",
		"{sample}/{sample}_peaks.bed",
		"{sample}/{sample}_unique_start_positions.bed",
		"{sample}/{sample}_intersect_annotated.bed",
		"{sample}/{sample}_big_table.tsv",
		"{sample}/{sample}_classified_peaks.bed",
		"{sample}/{sample}_custom_transduction.fasta",
		"{sample}/{sample}_transduction_plots.pdf",
		"{donor}_multi_peaks.bed"
		],
		sample=samples.index,
		donor=samples["donor"].unique()) 

rule qc: 
	input:
		raw_fastq1 = lambda wildcards: samples.loc[wildcards.sample]["raw_fastq1"],
		raw_fastq2 = lambda wildcards: samples.loc[wildcards.sample]["raw_fastq2"]
	output:
		illumina_adapter_trimmed_fastq1 = temp("{sample}/{sample}_illumina_adapter_trimmed_fastq1.gz"),
		illumina_adapter_trimmed_fastq2 = "{sample}/{sample}_illumina_adapter_trimmed_fastq2.gz",
		fastp_html_report = "{sample}/reports/{sample}_fastp.html",
		fastp_json_report = "{sample}/reports/{sample}_fastp.json"
	benchmark:
		"benchmarks/qc/{sample}.tsv"
	params:
		illumina_adapter = "AGATCGGAAGAGC",
		length_req = 50,
		report_path = lambda wildcards: f"{wildcards.sample}/reports"
	threads: 4
	resources:
		runtime = get_qc_runtime,
		mem_mb = get_qc_mem_mb
	shell:
		"fastp -w {threads} -a {params.illumina_adapter} --length_required={params.length_req} "
			"-i {input.raw_fastq1} -I {input.raw_fastq2} "
			"-o {output.illumina_adapter_trimmed_fastq1} -O {output.illumina_adapter_trimmed_fastq2} "
			"-h {output.fastp_html_report} "
			"-j {output.fastp_json_report} \n" # Run fastp 

		"mkdir -p {params.report_path} && "
			"fastqc -t {threads} --noextract --nogroup "
				"-o {params.report_path} "
				"{input.raw_fastq1} {input.raw_fastq2}" # Run fastqc 

rule preprocessing:
	input:
		illumina_adapter_trimmed_fastq1 = "{sample}/{sample}_illumina_adapter_trimmed_fastq1.gz", 
		illumina_adapter_trimmed_fastq2 = "{sample}/{sample}_illumina_adapter_trimmed_fastq2.gz",
	output:
		L1HS_adapter_trimmed_fromR2_fastq1 = temp("{sample}/{sample}_L1HS_adapter_trimmed_fromR2_fastq1.gz"),
		L1HS_adapter_trimmed_fromR2_fastq2 = "{sample}/{sample}_L1HS_adapter_trimmed_fromR2_fastq2.gz",
		L1HS_primer_trimmed_fromR2_fastq1 = temp("{sample}/{sample}_L1HS_primer_trimmed_fromR2_fastq1.gz"),
		L1HS_primer_trimmed_fromR2_fastq2 = temp("{sample}/{sample}_L1HS_primer_trimmed_fromR2_fastq2.gz"),
		subfamily_specific_R2_list = "{sample}/{sample}_subfamily_specific_R2_list.txt",
		L1HS_adapter_trimmed_fromR1_fastq1 = temp("{sample}/{sample}_L1HS_adapter_trimmed_fromR1_fastq1.gz"),
		L1HS_primer_trimmed_fromR1_fastq1 = temp("{sample}/{sample}_L1HS_primer_trimmed_fromR1_fastq1.gz"),
		L1HS_untrimmed_fromR1_fastq1 = temp("{sample}/{sample}_L1HS_untrimmed_fromR1_fastq1.gz"),
		mappable_R1_list = "{sample}/{sample}_mappable_R1_list.txt",
		mappable_R1_fastq1 = temp("{sample}/{sample}_mappable_R1_fastq1.gz"),
		mappable_R1_L1HSseq_trimmed_fromR1_fastq1 = "{sample}/{sample}_mappable_R1_L1HSsequence_trimmed_fromR1_fastq1.gz",
		mappable_R1_L1HSseq_polyA_trimmed_fromR1_fastq1 = "{sample}/{sample}_mappable_R1_L1HSsequence_polyA_fromR1_fastq1.gz",
		cutadapt_report = "{sample}/reports/{sample}_cutadapt_report.txt"
	benchmark:
		"benchmarks/preprocessing/{sample}.tsv"
	params:
		min_len = 5,
		min_len_informative = 70,
		min_ovlp = 20,
		max_err = 0.05,
		adapter_L1HS = lambda wildcards: samples.loc[wildcards.sample]["index_seq"] + "GGGAGATATACCTAATGCTAGATGACAC",
		adapter_primer = "^TTAGTGGGTGCAGCGCACCA",
		adapter_overlap_L1HS = "GTGTCATCTAGCATTAGGTATATCTCCC",
		adapter_overlap_primer = "TGGTGCGCTGCACCCACTAA$",
		L1PA_young_seq = "TTAGTGGGTGCAGCGCACCAGCATGGCACATGTATACATATGTAACTAACCTGCACAATGTGCACATGTACCCTAAAACTTAGAGT",
		L1HSseq = "ATTATACTCTAAGTTTTAGGGTACATGTGCACATTGTGCAGGTTAGTTACATATGTATACATGTGCCATGCTGGTGCGCTGCACCCACTAATGTGTCATCTAGCATTAGGTATATCTCCC",
		max_err_T = 0,
		adapter_T = "TTTTTTTT" 
	threads: 4
	resources:
		runtime = get_preprocessing_runtime,
		mem_mb = get_preprocessing_mem_mb
	log:
		"logs/preprocessing/{sample}.log"
	script:
		"scripts/preprocessing.sh"
		
rule alignment:
	input:
		ref_genome = REF_GENOME,
		mappable_R1_L1HSseq_trimmed_fromR1_fastq1 = "{sample}/{sample}_mappable_R1_L1HSsequence_trimmed_fromR1_fastq1.gz",
		mappable_R1_L1HSseq_polyA_trimmed_fromR1_fastq1 = "{sample}/{sample}_mappable_R1_L1HSsequence_polyA_fromR1_fastq1.gz"
	output:
		bwa_bam = temp("{sample}/{sample}_bwa.bam"),
		bwa_sorted_bam = "{sample}/{sample}_bwa_sorted.bam", 
		bwa_sorted_index = "{sample}/{sample}_bwa_sorted.bam.bai",
		trim_bwa_bam = temp("{sample}/{sample}_trim_bwa.bam"),
		trim_uniq_bam = temp("{sample}/{sample}_trim_uniq.bam"), 
		trim_uniq_sorted_bam = "{sample}/{sample}_trim_uniq_sorted.bam", # polyT-trimmed reads
		trim_uniq_sorted_index = "{sample}/{sample}_trim_uniq_sorted.bam.bai",
		trim_peaks = "{sample}/{sample}_trim_peaks.bed",
		peak_sorted_bam = "{sample}/{sample}_peak_sorted_bwa.bam",
		peak_sorted_index = "{sample}/{sample}_peak_sorted_bwa.bam.bai"
	benchmark:
		"benchmarks/alignment/{sample}.tsv"
	params:
		RG_ID = lambda wildcards: fr"@RG\tID:{TE_NAME}\tSM:{wildcards.sample}\tPL:{SEQ_PLATFORM}\tLB:HAT-seq\tCN:{SEQ_CENTER}",
	threads: 8
	resources:
		runtime = get_alignment_runtime,
		mem_mb = get_alignment_mem_mb
	log:
		"logs/alignment/{sample}.log"
	script:
		"scripts/alignment.sh"

rule Ntag:
	input:
		illumina_adapter_trimmed_fastq2 = "{sample}/{sample}_illumina_adapter_trimmed_fastq2.gz",
		mappable_R1_list = "{sample}/{sample}_mappable_R1_list.txt"
	output:
		Ntag_pre_fastq2 = temp("{sample}/{sample}_Ntag_pre_fastq2.gz"),
		Ntag_trimmed_fastq2 = temp("{sample}/{sample}_Ntag_trimmed_fastq2.gz"),
		Ntag_list = "{sample}/{sample}_Ntag_list.txt"
	benchmark:
		"benchmarks/Ntag/{sample}.tsv"
	params:
		adapter = lambda wildcards: samples.loc[wildcards.sample]["index_seq"] + "GGGAGATATACCTAATGCTAGATGACAC"
	resources:
		runtime = get_Ntag_runtime,
		mem_mb = get_Ntag_mem_mb
	shell:
		"seqtk subseq {input.illumina_adapter_trimmed_fastq2} {input.mappable_R1_list} | gzip - "
			"> {output.Ntag_pre_fastq2} \n"
		"cutadapt --quiet --discard-untrimmed -a {params.adapter} "
			"-o {output.Ntag_trimmed_fastq2} {output.Ntag_pre_fastq2} \n"
		"seqkit seq -i {output.Ntag_trimmed_fastq2} | "
			"seqtk seq -a - | "
			"awk '{{ if (NR%2) {{printf \"%s%s\", $0, \"\\t\"}} else {{printf \"%s%s\", $0, \"\\n\"}} }}' | "
			"grep '^>' | "
			"cut -b2- "
			"> {output.Ntag_list}"

rule gmotif:
	input:
		mappable_R1_list = "{sample}/{sample}_mappable_R1_list.txt",
		L1HS_adapter_trimmed_fromR2_fastq2 = "{sample}/{sample}_L1HS_adapter_trimmed_fromR2_fastq2.gz"
	output:
		pass_gmotif_list = "{sample}/{sample}_pass_gmotif_list.txt"
	benchmark:
		"benchmarks/gmotif/{sample}.tsv"
	resources:
		runtime = get_gmotif_runtime,
		mem_mb = get_gmotif_mem_mb
	shell:
		"seqtk subseq {input.L1HS_adapter_trimmed_fromR2_fastq2} {input.mappable_R1_list} | "
			"seqtk seq -a - | "
			"grep 'CTTAGAGT' -B 1 | "
			"seqkit seq -i -n - | sort | uniq "
			"> {output.pass_gmotif_list} \n"
	
rule extract_clipping:
	input:	
		peak_sorted_bam = "{sample}/{sample}_peak_sorted_bwa.bam"
	output:
		softclip3p_fasta = "{sample}/{sample}_softclip_3p.fa.gz",
		softclip5p_fasta = "{sample}/{sample}_softclip_5p.fa.gz",
		hardclip3p_table = "{sample}/{sample}_hardclip_3p.tsv",
		hardclip5p_table = "{sample}/{sample}_hardclip_5p.tsv"
	benchmark:
		"benchmarks/run_extract_clipping/{sample}.tsv"
	resources:
		runtime = get_extract_clipping_runtime,
		mem_mb = get_extract_clipping_mem_mb
	script:
		"scripts/extract_clipping.py"

rule junction_spanning:
	input:
		softclip3p_fasta = "{sample}/{sample}_softclip_3p.fa.gz"
	output:
		polyT_reads = "{sample}/{sample}_polyT_reads.txt"
	benchmark:
		"benchmarks/junction_spanning/{sample}.tsv"
	params:
		adapter_T = "TTTTTTTT" 
	resources:
		runtime = get_min_runtime,
		mem_mb = get_min_mem_mb
	shell:
		"zcat {input.softclip3p_fasta} | "
			"awk -v RS='>' -F '\n' 'substr($2,1,30) ~ \"{params.adapter_T}\" {{print $1}}' "
			"> {output.polyT_reads}"

rule peak_calling:
	input:
		peak_sorted_bam = "{sample}/{sample}_peak_sorted_bwa.bam",
		ref_genome = REF_GENOME,
		hg38 = HG38,
	output:
		peaks = "{sample}/{sample}_peaks.bed",
		max_depth = "{sample}/{sample}_max_depth_distance_to_boundary.txt",
		breakpoint_fa = "{sample}/{sample}_breakpoint.fa",
		peak_seq = "{sample}/{sample}_peak_sequence.fa"
	benchmark:
		"benchmarks/peak_calling/{sample}.tsv"
	resources:
		runtime = get_peak_calling_runtime,
		mem_mb = get_peak_calling_mem_mb
	log:
		"logs/peak_calling/{sample}.log"
	group: "peaks"
	script:
		"scripts/peak_calling.sh"

rule count_templates:
	input:
		peak_sorted_bam = "{sample}/{sample}_peak_sorted_bwa.bam",
		peaks = "{sample}/{sample}_peaks.bed"
	output:
		unique_start_positions = "{sample}/{sample}_unique_start_positions.bed",
		peak_readID_list = "{sample}/{sample}_peak_readID_list.txt"
	benchmark:
		"benchmarks/run_count_templates/{sample}.tsv"
	resources:
		runtime = get_count_templates_runtime,
		mem_mb = get_count_templates_mem_mb
	group: "peaks"
	script:
		"scripts/count_templates.py"

rule chimera:
	input:
		breakpoint_fa = "{sample}/{sample}_breakpoint.fa",
	output:
		chimera = "{sample}/{sample}_chimera.txt",
	benchmark:
		"benchmarks/run_chimera/{sample}.tsv"
	resources:
		runtime = get_min_runtime,
		mem_mb = get_min_mem_mb,
	group: "peaks"
	script:
		"scripts/chimera.py"

rule nearby_peak:
	input:
		peaks = "{sample}/{sample}_peaks.bed"
	output:
		nearby_peaks = "{sample}/{sample}_nearby_peaks.tsv"
	benchmark:
		"benchmarks/nearby_peak/{sample}.tsv"
	resources:
		runtime = get_min_runtime,
		mem_mb = get_min_mem_mb,
	group: "peaks"
	shell:
		"mergeBed -d 1000 -i {input.peaks} -c 4,5 -o collapse,collapse -delim \"=\" | "
			"awk '$4 ~ \"=\"' | "
			"awk '{{ OFS=\"\\t\"; split($5,a,\"=\"); split($4,b,\"=\"); max=0; stop=0; "
				"for(i=0; i<length(a); i++) "
					"{{split(a[i],d,\";\"); if(d[2] > max) {{max = d[2]; stop=i}} }} "
					"print b[stop],$4 }}' "
			"> {output.nearby_peaks} \n"

rule segdup:
	input:
		peaks = "{sample}/{sample}_peaks.bed",
		segdups = SEGDUPS
	output:
		segdup_intersect = "{sample}/{sample}_segdup_intersect.bed"
	benchmark:
		"benchmarks/segdup/{sample}.tsv"
	resources:
		runtime = get_min_runtime,
		mem_mb = get_min_mem_mb,
	group: "peaks"
	shell:
		"intersectBed -wao -a {input.peaks} -b {input.segdups} | "
			"mergeBed -s -i stdin -c 4,10 -o distinct,collapse "
			"> {output.segdup_intersect} \n"
				
rule intersect_databases:
	input:
		peaks = "{sample}/{sample}_peaks.bed",
		hg38 = HG38,  
		Evrony_KR = EVRONY_KR,
		repeat_masker = REPEAT_MASKER,
		homopolymers = HOMOPOLYMERS,
		i1kgp = I1KGP,
		gnomad = GNOMAD,
		nyuwa = NYUWA,
		xtea = XTEA,
		hgsvc3 = HGSVC3,
		melt_lra = HGSVC3_MELT_LRA,
		ont = ONT1019	
	output:
		intersect_annotated = "{sample}/{sample}_intersect_annotated.bed"
	benchmark:
		"benchmarks/intersect_databases/{sample}.tsv"
	resources:
		runtime = get_min_runtime,
		mem_mb = get_intersect_databases_mem_mb
	log:
		"logs/intersect_databases/{sample}.log"
	group: "peaks"
	script:
		"scripts/intersect_databases.sh"
		
rule create_big_table:
	input:
		peaks = "{sample}/{sample}_peaks.bed",
		peak_readID_list = "{sample}/{sample}_peak_readID_list.txt",
		intersect_annotated = "{sample}/{sample}_intersect_annotated.bed",
		chimera = "{sample}/{sample}_chimera.txt",
		pass_gmotif_list = "{sample}/{sample}_pass_gmotif_list.txt",
		Ntag_list = "{sample}/{sample}_Ntag_list.txt",
		unique_start_positions = "{sample}/{sample}_unique_start_positions.bed",
		nearby_peaks = "{sample}/{sample}_nearby_peaks.tsv",
		segdup_intersect = "{sample}/{sample}_segdup_intersect.bed",
		max_depth = "{sample}/{sample}_max_depth_distance_to_boundary.txt",
		polyT_reads = "{sample}/{sample}_polyT_reads.txt"
	output:
		big_table = "{sample}/{sample}_big_table.tsv"
	benchmark:
		"benchmarks/run_big_table/{sample}.tsv"
	resources:
		runtime = get_create_big_table_runtime,
		mem_mb = get_create_big_table_mem_mb
	group: "classify"
	script:
		"scripts/create_big_table.py"

rule filter_and_classify:
	input:
		big_table = "{sample}/{sample}_big_table.tsv",
	output:
		filter_reasons = "{sample}/{sample}_big_table_filter_reasons.tsv",
		classified_peaks = "{sample}/{sample}_classified_peaks.bed",
		plots = "{sample}/{sample}_filtering_plots.pdf",
		summary_file = "{sample}/{sample}_summary.txt",
		igv_script = "{sample}/{sample}_igv.sh"
	benchmark:
		"benchmarks/filter_and_classify/{sample}.tsv"
	params: 
		library = LIBRARY,
		error_prone = ERROR_PRONE,
		truth_set = TRUTH_SET, 
		path = lambda wildcards: os.getcwd() + f"/{wildcards.sample}/igv/"
	conda:
		"envs/plotR.yml"
	resources: 
		runtime = get_min_runtime,
		mem_mb = get_filter_and_classify_mem_mb,
	group: "classify"
	shell:
		"Rscript {workflow.basedir}/scripts/filter_and_plot.R "
			"{input.big_table} {output.filter_reasons} "
			"{params.library} {output.plots} "
			"{output.classified_peaks} {output.summary_file} "
			"{params.error_prone} {params.truth_set} \n"
		"grep -E 'UNK|SOM' {output.classified_peaks} | "
			"awk -v OFS='\t' '{{print $1,$2,$3,$4}}' | "
			"bedToIgv -name -slop 200 -path {params.path} -i stdin "
			"> {output.igv_script}"

rule map_transduction_fasta:
	input:
		classified_peaks = "{sample}/{sample}_classified_peaks.bed",
		ref_genome = REF_GENOME,
		L1HS_decoy = L1HS_DECOY,
		softclip3p_fasta = "{sample}/{sample}_softclip_3p.fa.gz",
		softclip5p_fasta = "{sample}/{sample}_softclip_5p.fa.gz",
		hardclip3p_table = "{sample}/{sample}_hardclip_3p.tsv",
		hardclip5p_table = "{sample}/{sample}_hardclip_5p.tsv",
		#cutadapt_report = "{sample}/reports/{sample}_cutadapt_report.txt"
	output:
		transduction_bed =  "{sample}/{sample}_custom_transduction.bed",
		transduction_fasta = "{sample}/{sample}_custom_transduction.fasta",
		transduction_fasta_index = "{sample}/{sample}_custom_transduction.fasta.bwt",
		softclip3p_trimmed_fasta = "{sample}/{sample}_softclip_3p_trimmed.fa.gz",
		softclip5p_trimmed_fasta = "{sample}/{sample}_softclip_5p_trimmed.fa.gz",
		softclip3p_trimmed_bam = "{sample}/{sample}_softclip_3p_trimmed.bam",
		softclip5p_trimmed_bam = "{sample}/{sample}_softclip_5p_trimmed.bam",
		softclip3p_trimmed_bed = "{sample}/{sample}_softclip_3p_trimmed.bed",
		softclip5p_trimmed_bed = "{sample}/{sample}_softclip_5p_trimmed.bed",
		hardclip3p_bed = "{sample}/{sample}_hardclip_3p.bed",
		hardclip5p_bed = "{sample}/{sample}_hardclip_5p.bed",
		transduction_report = "{sample}/reports/{sample}_transduction_report.txt"
	benchmark:
		"benchmarks/map_transduction_fasta/{sample}.tsv"
	params:
		adapter_T = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
		min_length = 10,
		RG_ID = lambda wildcards: fr"@RG\tID:{TE_NAME}\tSM:{wildcards.sample}\tPL:{SEQ_PLATFORM}\tLB:HAT-seq\tCN:{SEQ_CENTER}"
	threads: 4
	resources:
		runtime = get_map_transduction_fasta_runtime,
		mem_mb = get_map_transduction_fasta_mem_mb,
	log:
		"logs/map_transduction_fasta/{sample}.log"
	group: "transduction"
	script:
		"scripts/map_transduction_fasta.sh"

rule transduction_big_table: 
	input:
		peak_readID_list = "{sample}/{sample}_peak_readID_list.txt",
		hardclip3p_bed = "{sample}/{sample}_hardclip_3p.bed",
		hardclip5p_bed = "{sample}/{sample}_hardclip_5p.bed",
		softclip3p_trimmed_bed = "{sample}/{sample}_softclip_3p_trimmed.bed",
		softclip5p_trimmed_bed = "{sample}/{sample}_softclip_5p_trimmed.bed",
		transduction_bed =  "{sample}/{sample}_custom_transduction.bed",
	output:
		transduction_big_table = "{sample}/{sample}_transduction_big_table.tsv"
	benchmark:
		"benchmarks/run_transduction_big_table/{sample}.tsv"
	resources:
		runtime = get_transduction_big_table_runtime,
		mem_mb = get_transduction_big_table_mem_mb
	group: "transduction"
	script:
		"scripts/transduction_big_table.py"

rule call_transductions: 
	input: 
		transduction_bed = "{sample}/{sample}_custom_transduction.bed", 
		transduction_big_table = "{sample}/{sample}_transduction_big_table.tsv", 
		classified_peaks = "{sample}/{sample}_classified_peaks.bed"
	output:
		transduction_plots = "{sample}/{sample}_transduction_plots.pdf",
		filtered_transduction = "{sample}/{sample}_filtered_transduction.tsv"
	benchmark:
		"benchmarks/call_transductions/{sample}.tsv"
	conda:
		"envs/plotR.yml"
	resources:
		runtime = get_min_runtime, 
		mem_mb = get_call_transductions_mem_mb,
	group: "transduction"
	shell:
		"Rscript {workflow.basedir}/scripts/transduction_calling.R "
			"{input.transduction_big_table} {output.transduction_plots} "
			"{output.filtered_transduction} {input.transduction_bed} {input.classified_peaks} \n"

rule multi_sample_classification:
	input:
		sample_peaks = lambda wildcards: expand("{name}/{name}_classified_peaks.bed", 
												  name=get_donor_samples(wildcards, samples))
	output:
		donor_peaks = "all_{donor}_classified_peaks.bed",
		multi_peaks = "{donor}_multi_peaks.bed",
	benchmark:
		"benchmarks/multi_sample_classification/{donor}.tsv"
	params:
		num_samples = lambda wildcards, input: len(input.sample_peaks),
		comparison = get_comparison_string(samples)
	resources:
		runtime = get_min_runtime,
		mem_mb = get_filter_and_classify_mem_mb,
	group: "classify"
	shell:
			"python {workflow.basedir}/scripts/multi_classify.py "
				"-d {wildcards.donor} "
				"-f {input.sample_peaks} "
				"-p {output.donor_peaks} "
				"-m {output.multi_peaks} "
			"-c {params.comparison}"
		