#### Pipeline for preprocessing, aligning, calling, and filtering candidate L1HS insertions from HATseq libraries. ####

# Import required libraries
import pandas as pd
import os
import re
import gzip
import pysam
import numpy as np 
import math
import statistics
from snakemake.utils import validate

# Load helper functions
include: "rules/common.smk"

# Read config variables as constants
TE_NAME = config["te_name"]
REF_GENOME = config["bwa_ref_genome"]
REFERENCE_DIR = config["reference_dir"]
ERROR_PRONE = config.get("error_prone", "-NA-") # optional
LIBRARY = config["library"]
SEQ_PLATFORM = config['sequencing_platform']
SEQ_CENTER = config['sequencing_center']

# Read metadata
samples = pd.read_csv(config["metadata"], sep="\t", dtype=str)

# Validate configuration
config_schema = os.path.join(os.path.dirname(workflow.basedir), "config", "schemas", "config.schema.yml")
sample_schema = os.path.join(os.path.dirname(workflow.basedir), "config", "schemas", "samples.schema.yml")

validate(config, config_schema)
validate(samples, sample_schema)

# Format metadata
set_sample_names(samples, LIBRARY)
samples = samples.set_index("sample_name", drop=False)

# Create reference file constants
EVRONY_KR = REFERENCE_DIR + "/RepeatMasker/hg38.Evrony_KR_960.v37.revised.bed" # Lifted over
REPEAT_MASKER = REFERENCE_DIR + "/RepeatMasker/hg38.repeatmasker.bed"
HOMOPOLYMERS = REFERENCE_DIR + "/human/hg38.hg19.homo8.chr.bed" # Lifted over
SEGDUPS = REFERENCE_DIR + "/SegDup/hg38.genomicSuperDups.v37.chr.bed"
HG38 = REFERENCE_DIR + "/human/hg38.genome"
L1HS_DECOY = REFERENCE_DIR + "/L1HS_decoy_sequence.fasta"
I1KGP = REFERENCE_DIR + "/1kgp/ALL_MELT_ME_1000G_HC_20190901.AF.bed"
GNOMAD = REFERENCE_DIR + "/gnomAD-SV/gnomad.v4.1.ME.sites.bed" 
XTEA = REFERENCE_DIR + "/xTea/xTea_Borges-Monroy2021.accessioned.bed"
NYUWA = REFERENCE_DIR + "/nyuwa/MEI.GRCh38.HMEIDv1.1.final.bed"
HGSVC3 = REFERENCE_DIR + "/HGSVC3/MEI_Callset_GRCh38.ALL.20241211.bed"
HGSVC3_MELT_LRA = REFERENCE_DIR + "/HGSVC3/Ortho_MEI_GRCh38.ALL.20241211.bed"
ONT1019 = REFERENCE_DIR + "/1019_ONT/1019_ONT_Schloissnig2025.bed"

localrules: HATseq

rule HATseq:
	input:
		expand([
		"{sample}/{sample}_mappable_R1_list.txt",
		"{sample}/{sample}_peak_sorted_bwa.bam",
		"{sample}/{sample}_Ntag_list.txt",
		"{sample}/{sample}_pass_gmotif_list.txt",
		"{sample}/{sample}_polyT_reads.txt",
		"{sample}/{sample}_peaks.bed",
		"{sample}/{sample}_unique_start_positions.bed",
		"{sample}/{sample}_chimera_hash.txt",
		"{sample}/{sample}_intersect_annotated.bed",
		"{sample}/{sample}_big_table.tsv",
		"{sample}/{sample}_classified_peaks.bed",
		"{sample}/{sample}_custom_transduction.fasta",
		"{sample}/{sample}_transduction_plots.pdf",
		"{donor}_multi_peaks.bed"
		],
		sample=samples.index,
		donor=samples["donor"].unique()) 

rule qc: 
	input:
		raw_fastq1 = lambda wildcards: samples.loc[wildcards.sample]["raw_fastq1"],
		raw_fastq2 = lambda wildcards: samples.loc[wildcards.sample]["raw_fastq2"]
	output:
		illumina_adapter_trimmed_fastq1 = "{sample}/{sample}_illumina_adapter_trimmed_fastq1.gz",
		illumina_adapter_trimmed_fastq2 = "{sample}/{sample}_illumina_adapter_trimmed_fastq2.gz",
		fastp_html_report = "{sample}/reports/{sample}_fastp.html",
		fastp_json_report = "{sample}/reports/{sample}_fastp.json"
	benchmark:
		"benchmarks/qc/{sample}.tsv"
	params:
		illumina_adapter = "AGATCGGAAGAGC",
		length_req = 50,
		report_path = lambda wildcards: f"{wildcards.sample}/reports"
	threads: 4
	resources:
		runtime = get_qc_runtime,
		mem_mb = get_qc_mem_mb
	shell:
		"fastp -w {threads} -a {params.illumina_adapter} --length_required={params.length_req} "
			"-i {input.raw_fastq1} -I {input.raw_fastq2} "
			"-o {output.illumina_adapter_trimmed_fastq1} -O {output.illumina_adapter_trimmed_fastq2} "
			"-h {output.fastp_html_report} "
			"-j {output.fastp_json_report} \n" # Run fastp 

		"mkdir -p {params.report_path} && "
			"fastqc -t {threads} --noextract --nogroup "
				"-o {params.report_path} "
				"{input.raw_fastq1} {input.raw_fastq2}" # Run fastqc 

rule preprocessing:
	input:
		illumina_adapter_trimmed_fastq1 = "{sample}/{sample}_illumina_adapter_trimmed_fastq1.gz", 
		illumina_adapter_trimmed_fastq2 = "{sample}/{sample}_illumina_adapter_trimmed_fastq2.gz",
	output:
		L1HS_adapter_trimmed_fromR2_fastq1 = temp("{sample}/{sample}_L1HS_adapter_trimmed_fromR2_fastq1.gz"),
		L1HS_adapter_trimmed_fromR2_fastq2 = temp("{sample}/{sample}_L1HS_adapter_trimmed_fromR2_fastq2.gz"),
		L1HS_primer_trimmed_fromR2_fastq1 = temp("{sample}/{sample}_L1HS_primer_trimmed_fromR2_fastq1.gz"),
		L1HS_primer_trimmed_fromR2_fastq2 = "{sample}/{sample}_L1HS_primer_trimmed_fromR2_fastq2.gz",
		subfamily_specific_R2_list = "{sample}/{sample}_subfamily_specific_R2_list.txt",
		L1HS_adapter_trimmed_fromR1_fastq1 = temp("{sample}/{sample}_L1HS_adapter_trimmed_fromR1_fastq1.gz"),
		L1HS_primer_trimmed_fromR1_fastq1 = temp("{sample}/{sample}_L1HS_primer_trimmed_fromR1_fastq1.gz"),
		L1HS_untrimmed_fromR1_fastq1 = temp("{sample}/{sample}_L1HS_untrimmed_fromR1_fastq1.gz"),
		mappable_R1_list = "{sample}/{sample}_mappable_R1_list.txt",
		mappable_R1_fastq1 = "{sample}/{sample}_mappable_R1_fastq1.gz",
		mappable_R1_L1HSseq_trimmed_fromR1_fastq1 = "{sample}/{sample}_mappable_R1_L1HSsequence_trimmed_fromR1_fastq1.gz",
		mappable_R1_L1HSseq_polyA_trimmed_fromR1_fastq1 = "{sample}/{sample}_mappable_R1_L1HSsequence_polyA_fromR1_fastq1.gz",
		cutadapt_report = "{sample}/reports/{sample}_cutadapt_report.txt"
	benchmark:
		"benchmarks/preprocessing/{sample}.tsv"
	params:
		min_len = 5,
		min_len_informative = 70,
		min_ovlp = 20,
		max_err = 0.05,
		adapter_L1HS = lambda wildcards: samples.loc[wildcards.sample]["index_seq"] + "GGGAGATATACCTAATGCTAGATGACAC",
		adapter_primer = "^TTAGTGGGTGCAGCGCACCA",
		adapter_overlap_L1HS = "GTGTCATCTAGCATTAGGTATATCTCCC",
		adapter_overlap_primer = "TGGTGCGCTGCACCCACTAA$",
		L1PA_young_seq = "TTAGTGGGTGCAGCGCACCAGCATGGCACATGTATACATATGTAACTAACCTGCACAATGTGCACATGTACCCTAAAACTTAGAGT",
		L1HSseq = "ATTATACTCTAAGTTTTAGGGTACATGTGCACATTGTGCAGGTTAGTTACATATGTATACATGTGCCATGCTGGTGCGCTGCACCCACTAATGTGTCATCTAGCATTAGGTATATCTCCC",
		max_err_T = 0,
		adapter_T = "TTTTTTTT" 
	threads: 4
	resources:
		runtime = get_preprocessing_runtime,
		mem_mb = get_preprocessing_mem_mb
	shell:
		"set -x \n"

		# Remove the L1HS adapter from R2 filtering pairs where R2 does not contain the sequence. 
		# R1 and R2 fastqs are swapped and the sequence is with respect to the 5' of R2
		"cutadapt -j {threads} "
			"-m {params.min_len} -g {params.adapter_L1HS} --discard-untrimmed -O 10 -e 0.08 "
			"-p {output.L1HS_adapter_trimmed_fromR2_fastq1} -o {output.L1HS_adapter_trimmed_fromR2_fastq2} "
			"{input.illumina_adapter_trimmed_fastq2} {input.illumina_adapter_trimmed_fastq1} "
			">> {output.cutadapt_report} \n" 

		# Remove the L1HS primer from R2 filtering pairs where R2 does not contain the sequence. 
		# R1 and R2 fastqs are swapped and the sequence is with respect to the 5' of R2
		"cutadapt -j {threads} "
			"-m {params.min_len} -g {params.adapter_primer} --discard-untrimmed -O 5 -e 0.16 "
			"-p {output.L1HS_primer_trimmed_fromR2_fastq1} -o {output.L1HS_primer_trimmed_fromR2_fastq2} "
			"{output.L1HS_adapter_trimmed_fromR2_fastq2} {output.L1HS_adapter_trimmed_fromR2_fastq1} "
			">> {output.cutadapt_report} \n" 

		# Remove R2 that don't contain a sequence specific to the L1PA young subfamily of transposons
		"cutadapt -j {threads} "
			"--discard-untrimmed -g {params.L1PA_young_seq} -e 0.05 -O 20 "
			"{output.L1HS_adapter_trimmed_fromR2_fastq2} | "
			"seqkit seq -i -n - "
			"> {output.subfamily_specific_R2_list} \n" 
		
		# Remove the L1HS adapter from R1
		"cutadapt -j {threads} "
			"-m {params.min_len} -a {params.adapter_overlap_L1HS} -O 5 -e 0.08 "
			"-o {output.L1HS_adapter_trimmed_fromR1_fastq1} "
			"{output.L1HS_primer_trimmed_fromR2_fastq1} "
			">> {output.cutadapt_report} \n" 
		
		# Remove the L1HS primer from R1
		"cutadapt -j {threads} "
			"-m {params.min_len} -a {params.adapter_overlap_primer} -O 5 -e 0.16 "
			"--untrimmed-output {output.L1HS_untrimmed_fromR1_fastq1} "
			"-o {output.L1HS_primer_trimmed_fromR1_fastq1} "
			"{output.L1HS_adapter_trimmed_fromR1_fastq1} "
			">> {output.cutadapt_report} \n" 
		
		"cutadapt -j {threads} "
			"-m {params.min_len_informative} "
			"{output.L1HS_primer_trimmed_fromR1_fastq1} | "
			"seqtk subseq - {output.subfamily_specific_R2_list} | "
			"seqkit seq -i -n -  "
			"> {output.mappable_R1_list} \n"

		# Create list of R1s that have a pair that passed 
		"seqtk subseq {output.L1HS_untrimmed_fromR1_fastq1} {output.subfamily_specific_R2_list} | "
			"seqkit seq -i -n -  "
			">> {output.mappable_R1_list} \n" 

		"seqtk subseq {output.L1HS_adapter_trimmed_fromR2_fastq1} {output.mappable_R1_list} | gzip - "
			"> {output.mappable_R1_fastq1} \n" 

		"cutadapt -j {threads} "
			"-m {params.min_len} -a {params.L1HSseq} -O {params.min_ovlp} -e {params.max_err} "
			"-o {output.mappable_R1_L1HSseq_trimmed_fromR1_fastq1} "
			"{output.mappable_R1_fastq1} "
			">> {output.cutadapt_report} \n"

		"cutadapt -a {params.adapter_T} -e {params.max_err_T} "
			"-o {output.mappable_R1_L1HSseq_polyA_trimmed_fromR1_fastq1} "
			"{output.mappable_R1_L1HSseq_trimmed_fromR1_fastq1} "
			">> {output.cutadapt_report} \n"		
		
rule alignment:
	input:
		ref_genome = REF_GENOME,
		mappable_R1_L1HSseq_trimmed_fromR1_fastq1 = "{sample}/{sample}_mappable_R1_L1HSsequence_trimmed_fromR1_fastq1.gz",
		mappable_R1_L1HSseq_polyA_trimmed_fromR1_fastq1 = "{sample}/{sample}_mappable_R1_L1HSsequence_polyA_fromR1_fastq1.gz"
	output:
		bwa_bam = temp("{sample}/{sample}_bwa.bam"),
		bwa_sorted_bam = "{sample}/{sample}_bwa_sorted.bam", 
		bwa_sorted_index = "{sample}/{sample}_bwa_sorted.bam.bai",
		trim_bwa_bam = temp("{sample}/{sample}_trim_bwa.bam"),
		trim_uniq_bam = temp("{sample}/{sample}_trim_uniq.bam"), 
		trim_uniq_sorted_bam = "{sample}/{sample}_trim_uniq_sorted.bam", # polyT-trimmed reads
		trim_uniq_sorted_index = "{sample}/{sample}_trim_uniq_sorted.bam.bai",
		trim_peaks = "{sample}/{sample}_trim_peaks.bed",
		peak_sorted_bam = "{sample}/{sample}_peak_sorted_bwa.bam",
		peak_sorted_index = "{sample}/{sample}_peak_sorted_bwa.bam.bai"
	benchmark:
		"benchmarks/alignment/{sample}.tsv"
	params:
		RG_ID = lambda wildcards: fr"-R '@RG\tID:{TE_NAME}\tSM:{wildcards.sample}\tPL:{SEQ_PLATFORM}\tLB:HAT-seq\tCN:{SEQ_CENTER}'"
	threads: 8 
	resources:
		runtime = get_alignment_runtime,
		mem_mb = get_alignment_mem_mb
	shell:
		# Map mappable parts of R1 to reference genome
		"bwa mem -t {threads} {params.RG_ID} {input.ref_genome} {input.mappable_R1_L1HSseq_trimmed_fromR1_fastq1} | "
			"samtools view -Sb - "
			"> {output.bwa_bam} \n"
		"samtools sort -o {output.bwa_sorted_bam} {output.bwa_bam} \n"
		"samtools index {output.bwa_sorted_bam} \n"

		"bwa mem -t {threads} {params.RG_ID} {input.ref_genome} {input.mappable_R1_L1HSseq_polyA_trimmed_fromR1_fastq1} | "
			"samtools view -Sb - "
			"> {output.trim_bwa_bam} \n"
			
		# Unique read = read with MAPQ >= 20 and edit distance < 4
		"samtools view -q 20 {output.trim_bwa_bam} | "
			"awk '{{ for (i=1;i<=NF;i++) "
				"{{ if ($i ~/AS:i:/) "
					"{{split ($i,a,\":\")}}; "
				"if ($i ~/XS:i:/) "
					"{{split ($i,b,\":\")}} }}; "
				"if (a[3]>b[3]) print; }}' | "
			"awk '{{ for (i=1;i<=NF;i++) "
				"{{ if ($i ~/NM:i:/) "
					"{{split ($i,a,\":\"); "
				"if (a[3]<4) print; }} }} }}' | "
			"cat <(samtools view -H {output.trim_bwa_bam}) - | "
			"samtools view -Sb - "
			"> {output.trim_uniq_bam} \n"
		"samtools sort -o {output.trim_uniq_sorted_bam} {output.trim_uniq_bam} \n"
		"samtools index {output.trim_uniq_sorted_bam} \n"

		# Find regions (peak) with at least 1 unique read 
		"cat <( genomeCoverageBed -ibam {output.trim_uniq_sorted_bam} -bg -strand \"+\" | "
			"awk '{{OFS=\"\\t\"; print $1,$2,$3,$4,\".\",\"+\",$3-$2}}' ) "
			"<( genomeCoverageBed -ibam {output.trim_uniq_sorted_bam} -bg -strand \"-\" | "
			"awk '{{OFS=\"\\t\"; print $1,$2,$3,$4,\".\",\"-\",$3-$2}}' ) | "
			"sort -k1,1 -k2,2n | "
			"mergeBed -d 1 -i stdin -s -c 1,4,6,7,4 -o count,collapse,distinct,collapse,max | "
			"awk '{{ OFS=\"\\t\"; "
				"if($6 == \"+\") "
					"{{print $1,$2,$3,\"{wildcards.sample}-plus-peak-\"NR,$4\";\"$8\";\"$7\";\"$5,$6}} "
				"else "
					"{{print $1,$2,$3,\"{wildcards.sample}-minus-peak-\"NR,$4\";\"$8\";\"$7\";\"$5,$6}} }}' "
			">> {output.trim_peaks} \n"

		# Output all reads in peak regions
		"samtools view --region-file {output.trim_peaks} {output.bwa_sorted_bam} | "
			"cat <(samtools view -H {output.bwa_bam}) - | "
			"samtools sort -o {output.peak_sorted_bam} - \n"
		"sambamba index {output.peak_sorted_bam} \n"

rule Ntag:
	input:
		illumina_adapter_trimmed_fastq2 = "{sample}/{sample}_illumina_adapter_trimmed_fastq2.gz",
		mappable_R1_list = "{sample}/{sample}_mappable_R1_list.txt"
	output:
		Ntag_pre_fastq2 = "{sample}/{sample}_Ntag_pre_fastq2.gz",
		Ntag_trimmed_fastq2 = "{sample}/{sample}_Ntag_trimmed_fastq2.gz",
		Ntag_list = "{sample}/{sample}_Ntag_list.txt"
	benchmark:
		"benchmarks/Ntag/{sample}.tsv"
	params:
		adapter = lambda wildcards: samples.loc[wildcards.sample]["index_seq"] + "GGGAGATATACCTAATGCTAGATGACAC"
	resources:
		runtime = get_Ntag_runtime,
		mem_mb = get_Ntag_mem_mb
	shell:
		"seqtk subseq {input.illumina_adapter_trimmed_fastq2} {input.mappable_R1_list} | gzip - "
			"> {output.Ntag_pre_fastq2} \n"
		"cutadapt --quiet --discard-untrimmed -a {params.adapter} "
			"-o {output.Ntag_trimmed_fastq2} {output.Ntag_pre_fastq2} \n"
		"seqkit seq -i {output.Ntag_trimmed_fastq2} | "
			"seqtk seq -a - | "
			"awk '{{ if (NR%2) {{printf \"%s%s\", $0, \"\\t\"}} else {{printf \"%s%s\", $0, \"\\n\"}} }}' | "
			"grep '^>' | "
			"cut -b2- "
			"> {output.Ntag_list}"

rule gmotif:
	input:
		mappable_R1_list = "{sample}/{sample}_mappable_R1_list.txt",
		L1HS_adapter_trimmed_fromR2_fastq2 = "{sample}/{sample}_L1HS_adapter_trimmed_fromR2_fastq2.gz"
	output:
		pass_gmotif_list = "{sample}/{sample}_pass_gmotif_list.txt"
	benchmark:
		"benchmarks/gmotif/{sample}.tsv"
	resources:
		runtime = get_gmotif_runtime,
		mem_mb = get_gmotif_mem_mb
	shell:
		"seqtk subseq {input.L1HS_adapter_trimmed_fromR2_fastq2} {input.mappable_R1_list} | "
			"seqtk seq -a - | "
			"grep 'CTTAGAGT' -B 1 | "
			"seqkit seq -i -n - | sort | uniq "
			"> {output.pass_gmotif_list} \n"
	
rule extract_clipping:
	input:	
		peak_sorted_bam = "{sample}/{sample}_peak_sorted_bwa.bam"
	output:
		softclip3p_fasta = "{sample}/{sample}_softclip_3p.fa.gz",
		softclip5p_fasta = "{sample}/{sample}_softclip_5p.fa.gz",
		hardclip3p_table = "{sample}/{sample}_hardclip_3p.tsv",
		hardclip5p_table = "{sample}/{sample}_hardclip_5p.tsv"
	benchmark:
		"benchmarks/run_extract_clipping/{sample}.tsv"
	resources:
		runtime = get_extract_clipping_runtime,
		mem_mb = get_extract_clipping_mem_mb
	run:
		ofasta5p=gzip.open(output.softclip5p_fasta, 'wt')
		otable5p=open(output.hardclip5p_table, 'w')
		ofasta3p=gzip.open(output.softclip3p_fasta, 'wt')
		otable3p=open(output.hardclip3p_table, 'w')
		
		def reverse_complement(seq):
			complement = {'A':'T', 'T':'A', 'G':'C', 'C':'G', 'N':'N'}
			return ''.join(complement[base] for base in reversed(seq))

		ibam=pysam.AlignmentFile(input.peak_sorted_bam, 'rb')
		for read in ibam.fetch(until_eof=True):
			reverse = (read.flag & 16 == 16) 
			if "S" in read.cigarstring:
				if read.cigartuples[0][0] == 4 :
					if reverse: # reverse read and clip is at reference 3' = 5' clipping
						ofasta3p.write(">" + read.query_name + "\n")
						ofasta3p.write(reverse_complement(read.query_sequence[0:read.query_alignment_start-1]) + "\n")
					else:
						ofasta5p.write(">" + read.query_name + "\n")
						ofasta5p.write(read.query_sequence[0:read.query_alignment_start-1] + "\n")	
				elif read.cigartuples[len(read.cigartuples)-1][0] == 4:
					if reverse:
						ofasta5p.write(">" + read.query_name + "\n")
						ofasta5p.write(reverse_complement(read.query_sequence[read.query_alignment_end+1:read.query_length-1]) + "\n")
					else:
						ofasta3p.write(">" + read.query_name + "\n")
						ofasta3p.write(read.query_sequence[read.query_alignment_end+1:read.query_length-1] + "\n")

			if "H" in read.cigarstring:
				if read.cigartuples[0][0] == 5:
					num_alt_mappings = len(read.get_tag("SA").strip(";").split(";"))
					if num_alt_mappings == 1:
						uniq_supp_map = read.get_tag("SA").strip(";").split(";")[0].split(",")
						if int(uniq_supp_map[4]) > 20 and int(uniq_supp_map[5]) < 4: 
							if reverse:
								otable3p.write(read.query_name + "\t" + str(uniq_supp_map[0]) + ":" +  str(uniq_supp_map[1]) + "-" + str(int(uniq_supp_map[1]) + int(read.reference_length)) + ":" + uniq_supp_map[2] + "\n")
							else:
								otable5p.write(read.query_name + "\t" + str(uniq_supp_map[0]) + ":" +  str(uniq_supp_map[1]) + "-" + str(int(uniq_supp_map[1]) + int(read.reference_length)) + ":" + uniq_supp_map[2] + "\n")

				elif read.cigartuples[len(read.cigartuples)-1][0] == 5:
					num_alt_mappings = len(read.get_tag("SA").strip(";").split(";"))
					if num_alt_mappings == 1:
						uniq_supp_map = read.get_tag("SA").strip(";").split(";")[0].split(",")
						if int(uniq_supp_map[4]) > 20 and int(uniq_supp_map[5]) < 4:
							if reverse:
								otable5p.write(read.query_name + "\t" + str(uniq_supp_map[0]) + ":" +  str(uniq_supp_map[1]) + "-" + str(int(uniq_supp_map[1]) + int(read.reference_length)) + ":" + uniq_supp_map[2] + "\n")
							else:
								otable3p.write(read.query_name + "\t" + str(uniq_supp_map[0]) + ":" +  str(uniq_supp_map[1]) + "-" + str(int(uniq_supp_map[1]) + int(read.reference_length)) + ":" + uniq_supp_map[2] + "\n")		

		ofasta5p.close()
		otable5p.close()
		ofasta3p.close()
		otable3p.close()	

rule junction_spanning:
	input:
		softclip3p_fasta = "{sample}/{sample}_softclip_3p.fa.gz"
	output:
		polyT_reads = "{sample}/{sample}_polyT_reads.txt"
	benchmark:
		"benchmarks/junction_spanning/{sample}.tsv"
	params:
		adapter_T = "TTTTTTTT" 
	resources:
		runtime = get_min_runtime,
		mem_mb = get_min_mem_mb
	shell:
		"zcat {input.softclip3p_fasta} | "
			"awk -v RS='>' -F '\n' 'substr($2,1,30) ~ \"{params.adapter_T}\" {{print $1}}' "
			"> {output.polyT_reads}"

rule peak_calling:
	input:
		peak_sorted_bam = "{sample}/{sample}_peak_sorted_bwa.bam",
		ref_genome = REF_GENOME,
		hg38 = HG38,
	output:
		peaks = "{sample}/{sample}_peaks.bed",
		max_depth = "{sample}/{sample}_max_depth_distance_to_boundary.txt",
		breakpoint_fa = "{sample}/{sample}_breakpoint.fa",
		peak_seq = "{sample}/{sample}_peak_sequence.fa"
	benchmark:
		"benchmarks/peak_calling/{sample}.tsv"
	resources:
		runtime = get_peak_calling_runtime,
		mem_mb = get_peak_calling_mem_mb
	group: "peaks"
	shell:
		"echo '#chr\tstart\tend\tpeak_name\tnum_subpeaks;max_depth;length_subpeaks;depth_subpeaks\tstrand' "
			"> {output.peaks} \n"

		"cat <( genomeCoverageBed -ibam {input.peak_sorted_bam} -bg -strand \"+\" | "
			"awk '{{OFS=\"\\t\"; print $1,$2,$3,$4,\".\",\"+\",$3-$2}}' ) "
			"<( genomeCoverageBed -ibam {input.peak_sorted_bam} -bg -strand \"-\" | "
			"awk '{{OFS=\"\\t\"; print $1,$2,$3,$4,\".\",\"-\",$3-$2}}' ) | "
			"sort -k1,1 -k2,2n | "
			"mergeBed -d 1 -i stdin -s -c 1,4,6,7,4 -o count,collapse,distinct,collapse,max | "
			"awk '{{ OFS=\"\\t\"; "
				"if($6 == \"+\") "
					"{{print $1,$2,$3,\"{wildcards.sample}-plus-peak-\"NR,$4\";\"$8\";\"$7\";\"$5,$6}} "
				"else "
					"{{print $1,$2,$3,\"{wildcards.sample}-minus-peak-\"NR,$4\";\"$8\";\"$7\";\"$5,$6}} }}' "
			">> {output.peaks} \n"

		"awk '{{ OFS=\"\\t\"; "
			"split($5,a,\";\"); split(a[4],b,\",\"); split(a[3],c,\",\"); "
			"sum=0; stop=1; "
			"if($6 == \"+\") "
				"{{ for(i=length(b);i>0; i=i-1) "
					"{{ if(b[i] < a[2]) "
						"{{sum=sum+(stop*c[i])}} "
					"else "
						"{{stop=0}} }} }} "
			"else "
				"{{ for(i=1;i<length(b)+1; i=i+1) "
					"{{ if(b[i] < a[2]) "
						"{{sum=sum+(stop*c[i])}} "
					"else "
						"{{stop=0}} }} }} print $4,sum }}' {output.peaks} "
			"> {output.max_depth} \n"

		"slopBed -l 30 -r 0 -s -g {input.hg38} "
			"-i <(awk '{{ OFS=\"\\t\"; "
				"if($6 == \"-\") "
					"{{print $1,$2,$2+1,$4,$5,$6}} "
				"else "
					"{{print $1,$3,$3+1,$4,$5,$6}} }}' {output.peaks}) | "
			"bedtools getfasta -fi {input.ref_genome} -bed stdin -name "
			"> {output.breakpoint_fa} \n"

		"bedtools getfasta -fi {input.ref_genome} -bed {output.peaks} -name > {output.peak_seq} \n"

rule count_templates:
	input:
		peak_sorted_bam = "{sample}/{sample}_peak_sorted_bwa.bam",
		peaks = "{sample}/{sample}_peaks.bed"
	output:
		unique_start_positions = "{sample}/{sample}_unique_start_positions.bed",
		peak_readID_list = "{sample}/{sample}_peak_readID_list.txt"
	benchmark:
		"benchmarks/run_count_templates/{sample}.tsv"
	resources:
		runtime = get_count_templates_runtime,
		mem_mb = get_count_templates_mem_mb
	group: "peaks"
	run:
		ibam=pysam.AlignmentFile(input.peak_sorted_bam,'rb')
		ibed=open(input.peaks, 'r')
		obed=open(output.unique_start_positions, 'w')
		header = ["#peak_name", "num_bam_reads", "num_peak_reads", "num_usp;depth", 
				  "max_neighbor_difference", "median_neighbor_difference", "mean_neighbor_difference"]
		obed.write("\t".join(header) + "\n")
		ibam_total_reads = sum([i[3] for i in ibam.get_index_statistics()])
		peak_readID_list = []
		for peak_line in ibed:
			if peak_line.startswith("#"):
				continue
			peak = peak_line.strip().split("\t")
			peak_iter = ibam.fetch(peak[0], int(peak[1]), int(peak[2]))
			this_peak_usp_dictionary = {}
			for read in peak_iter:
				if read.is_reverse:
					key = read.reference_name + ":" + str(read.reference_end)
				else:
					key = read.reference_name + ":" + str(read.reference_start)

				if peak[5] == "-":
					if read.is_reverse:
						if not key in this_peak_usp_dictionary.keys():
							this_peak_usp_dictionary[key] = (0,0)
						peak_readID_list.append([peak[3], read.query_name])

						this_peak_usp_dictionary[key] = (this_peak_usp_dictionary[key][0]+1,
														 this_peak_usp_dictionary[key][1]+1)
				elif peak[5] == "+":
					if not read.is_reverse:
						if not key in this_peak_usp_dictionary.keys():
							this_peak_usp_dictionary[key] = (0,0)
						peak_readID_list.append([peak[3], read.query_name])

						this_peak_usp_dictionary[key] = (this_peak_usp_dictionary[key][0]+1,
														 this_peak_usp_dictionary[key][1]+1)
			this_peak_total_reads = sum([this_peak_usp_dictionary[key][1] for key in this_peak_usp_dictionary.keys()])
			duplicates_list = [this_peak_usp_dictionary[key][1] for key in this_peak_usp_dictionary.keys()]
			difference_list = []
			if(len(duplicates_list) > 1):
				for i in range(0,len(duplicates_list)-1):
					difference_list.append(abs(duplicates_list[i] - duplicates_list[i+1]))
			else:
				difference_list = [-1]

			duplicates_list.sort(reverse=True)

			obed.write(peak[3] + "\t" + str(ibam_total_reads) + "\t" + str(this_peak_total_reads) + "\t" + str(len(this_peak_usp_dictionary.keys())) + ";" + ",".join(map(str, duplicates_list)) + "\t" + str(max(difference_list)) + "\t" + str(statistics.median(difference_list)) + "\t" + str(statistics.mean(difference_list)) + "\n") 
		with open(output.peak_readID_list, 'w') as list:
			for peak_read in peak_readID_list:
				list.write("\t".join(peak_read) + "\n")
		obed.close()
		ibed.close()

rule chimera:
	input:
		breakpoint_fa = "{sample}/{sample}_breakpoint.fa",
		peak_seq = "{sample}/{sample}_peak_sequence.fa"
	output:
		chimera = "{sample}/{sample}_chimera.txt",
		nonchimera = "{sample}/{sample}_nonchimera.txt",
		misalignment = "{sample}/{sample}_misalignment.txt"
	benchmark:
		"benchmarks/run_chimera/{sample}.tsv"
	resources:
		runtime = get_min_runtime,
		mem_mb = get_min_mem_mb,
	group: "peaks"
	run:
		chimera_list = []
		nonchimera_list = []
		misalignment_list = []
		with open(input.breakpoint_fa) as fa:
			peak = fa.readline().strip("\n").strip(">")
			seq = fa.readline().strip("\n").upper()
			while(peak):
				if "minus" in peak:
					chimera = "A"
				else:
					chimera = "T"
				overall_max = 0
				i = 0	
				while i < len(seq):
					if seq[i] == chimera:
						cur_max = 1
						i = i+1
						if i < len(seq):
							while seq[i] == chimera:
								cur_max = cur_max + 1
								i = i + 1
								if i == len(seq):
									break
						if cur_max > overall_max:
							overall_max = cur_max
					i = i+1
				if overall_max > 12 or (seq.count(chimera) / len(seq)) >= 0.8:
					chimera_list.append(peak)
				else:
					nonchimera_list.append(peak)
				peak = fa.readline().strip("\n").strip(">")
				seq = fa.readline().strip("\n").upper()

		with open(input.peak_seq) as fa:
			peak = fa.readline().strip("\n").strip(">")
			seq = fa.readline().strip("\n").upper()
			while(peak):
				if "minus" in peak:
					chimera = "A"
				else:
					chimera = "T"
				if (seq.count(chimera)/ len(seq) > 0.5): 
					misalignment_list.append(peak)
				peak = fa.readline().strip("\n").strip(">")
				seq = fa.readline().strip("\n").upper()
				
		with open(output.misalignment,'w') as mis:
			mis.write("\n".join(misalignment_list))		
		with open(output.chimera,'w') as chim:
			chim.write("\n".join(chimera_list))
		with open(output.nonchimera,'w') as nonchim:
			nonchim.write("\n".join(nonchimera_list))

rule chimera_hash:
	input:
		breakpoint_fa = "{sample}/{sample}_breakpoint.fa"
	output:
		chimera_hash = "{sample}/{sample}_chimera_hash.txt"
	benchmark:
		"benchmarks/run_chimera_hash/{sample}.tsv"
	resources:
		runtime = get_min_runtime,
		mem_mb = get_min_mem_mb,
	group: "peaks"
	run:
		seqs = open(input.breakpoint_fa , 'r')
		peak = seqs.readline().strip("\n").strip(">") 
		seq = seqs.readline().strip("\n").upper()
		hash = ['AA', 'AC', 'AG', 'AT', 'CA', 'CC', 'CG', 'CT', 'GA', 'GC', 'GG', 'GT', 'TA', 'TC', 'TG', 'TT' ]

		with open(output.chimera_hash, 'w') as chim:
			chim.write("peak\t" + "\t".join(hash) + "\twidth\n")
			while(peak):
				minus_peak = ("minus" in peak)
				peak_hash = []
				for key in hash:
					# Get percent of total possible dimers for each unique dimer
					peak_hash.append(str(seq.count(key) / (len(seq) -2))) 
				chim.write(peak + "\t" + "\t".join(peak_hash)  + "\t" + str(len(seq)) + "\n")
				peak = seqs.readline().strip("\n").strip(">")
				seq = seqs.readline().strip("\n").upper()

rule nearby_peak:
	input:
		peaks = "{sample}/{sample}_peaks.bed"
	output:
		nearby_peaks = "{sample}/{sample}_nearby_peaks.tsv"
	benchmark:
		"benchmarks/nearby_peak/{sample}.tsv"
	resources:
		runtime = get_min_runtime,
		mem_mb = get_min_mem_mb,
	group: "peaks"
	shell:
		"mergeBed -d 1000 -i {input.peaks} -c 4,5 -o collapse,collapse -delim \"=\" | "
			"awk '$4 ~ \"=\"' | "
			"awk '{{ OFS=\"\\t\"; split($5,a,\"=\"); split($4,b,\"=\"); max=0; stop=0; "
				"for(i=0; i<length(a); i++) "
					"{{split(a[i],d,\";\"); if(d[2] > max) {{max = d[2]; stop=i}} }} "
					"print b[stop],$4 }}' "
			"> {output.nearby_peaks} \n"

rule segdup:
	input:
		peaks = "{sample}/{sample}_peaks.bed",
		segdups = SEGDUPS
	output:
		segdup_intersect = "{sample}/{sample}_segdup_intersect.bed"
	benchmark:
		"benchmarks/segdup/{sample}.tsv"
	resources:
		runtime = get_min_runtime,
		mem_mb = get_min_mem_mb,
	group: "peaks"
	shell:
		"bedtools intersect -wao -a {input.peaks} -b {input.segdups} | "
			"bedtools merge -s -i stdin -c 4,10 -o distinct,collapse "
			"> {output.segdup_intersect} \n"
				
rule intersect_databases:
	input:
		peaks = "{sample}/{sample}_peaks.bed",
		hg38 = HG38,  
		Evrony_KR = EVRONY_KR,
		repeat_masker = REPEAT_MASKER,
		homopolymers = HOMOPOLYMERS,
		i1kgp = I1KGP,
		gnomad = GNOMAD,
		nyuwa = NYUWA,
		xtea = XTEA,
		hgsvc3 = HGSVC3,
		melt_lra = HGSVC3_MELT_LRA,
		ont = ONT1019	
	output:
		intersect_annotated = "{sample}/{sample}_intersect_annotated.bed"
	benchmark:
		"benchmarks/intersect_databases/{sample}.tsv"
	resources:
		runtime = get_min_runtime,
		mem_mb = get_intersect_databases_mem_mb
	group: "peaks"
	shell:
		"echo '#chr\tstart\tend\tpeak_name\tnum_subpeaks;max_depth;length_subpeaks;depth_subpeaks\tstrand\t"
			"RepeatMasker\tEvrony_KR\tHomopolymers\t"
			"1000_Genomes_Project\tgnomAD\tNyuWa\txTea\tHGSVC3\tHGSVC3-MELT-LRA\t1019_ONT' "
			"> {output.intersect_annotated} \n"
		"bedtools intersect -S -wao -a {input.peaks} -b <(slopBed -g {input.hg38} -l 0 -r 500 -s -i {input.repeat_masker}) | "
			"awk '{{OFS=\"\\t\"; print $1,$2,$3,$4,$5,$6,$10\";\"$11\";\"$12}}' | "
			"bedtools groupby -grp 1,2,3,4,5,6 -c 7 -o collapse | "
			"bedtools intersect -S -wao -a stdin -b <(slopBed -g {input.hg38} -l 0 -r 500 -s -i {input.Evrony_KR}) | "
			"awk '{{OFS=\"\\t\"; print $1,$2,$3,$4,$5,$6,$7,$11\";\"$12\";\"$13}}' | "
			"bedtools groupby -grp 1,2,3,4,5,6,7 -c 8 -o collapse | "
			"bedtools intersect -wao -a stdin -b <(slopBed -g {input.hg38} -l 0 -r 500 -s -i {input.homopolymers}) | "
			"awk '{{OFS=\"\\t\"; print $1,$2,$3,$4,$5,$6,$7,$8,$12}}' | "
			"bedtools groupby -grp 1,2,3,4,5,6,7,8 -c 9 -o collapse | "
			"bedtools intersect -wao -a stdin -b <(slopBed -g {input.hg38} -b 500 -s -i {input.i1kgp}) | "
			"awk '{{OFS=\"\\t\"; print $1,$2,$3,$4,$5,$6,$7,$8,$9,$13\";\"$14\";\"$15}}' | "
			"bedtools groupby -grp 1,2,3,4,5,6,7,8,9 -c 10 -o collapse | "
			"bedtools intersect -wao -a stdin -b <(slopBed -g {input.hg38} -b 500 -s -i {input.gnomad}) | "
			"awk '{{OFS=\"\\t\"; print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$14\";\"$15}}' | "
			"bedtools groupby -grp 1,2,3,4,5,6,7,8,9,10 -c 11 -o collapse | "
			"bedtools intersect -wao -a stdin -b <(slopBed -g {input.hg38} -b 500 -s -i {input.nyuwa}) | "
			"awk '{{OFS=\"\\t\"; print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$15\";\"$16}}' | "
			"bedtools groupby -grp 1,2,3,4,5,6,7,8,9,10,11 -c 12 -o collapse | "
			"bedtools intersect -wao -a stdin -b <(slopBed -g {input.hg38} -b 500 -s -i {input.xtea}) | "
			"awk '{{OFS=\"\\t\"; print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$16\";\"$17\";\"$18}}' | "
			"bedtools groupby -grp 1,2,3,4,5,6,7,8,9,10,11,12 -c 13 -o collapse | "
			"bedtools intersect -wao -a stdin -b <(slopBed -g {input.hg38} -b 500 -s -i {input.hgsvc3}) | "
			"awk '{{OFS=\"\\t\"; print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$17\";\"$18}}' | "
			"bedtools groupby -grp 1,2,3,4,5,6,7,8,9,10,11,12,13 -c 14 -o collapse | "
			"bedtools intersect -wao -a stdin -b <(slopBed -g {input.hg38} -b 500 -s -i {input.melt_lra}) | "
			"awk '{{OFS=\"\\t\"; print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$18\";\"$19}}' | "
			"bedtools groupby -grp 1,2,3,4,5,6,7,8,9,10,11,12,13,14 -c 15 -o collapse | "
			"bedtools intersect -wao -a stdin -b <(slopBed -g {input.hg38} -b 500 -s -i {input.ont}) | "
			"awk '{{OFS=\"\\t\"; print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$19}}' | "
			"bedtools groupby -grp 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 -c 16 -o collapse "
			">> {output.intersect_annotated} \n"
		
rule create_big_table:
	input:
		peaks = "{sample}/{sample}_peaks.bed",
		peak_readID_list = "{sample}/{sample}_peak_readID_list.txt",
		intersect_annotated = "{sample}/{sample}_intersect_annotated.bed",
		chimera = "{sample}/{sample}_chimera.txt",
		nonchimera = "{sample}/{sample}_nonchimera.txt",
		pass_gmotif_list = "{sample}/{sample}_pass_gmotif_list.txt",
		Ntag_list = "{sample}/{sample}_Ntag_list.txt",
		unique_start_positions = "{sample}/{sample}_unique_start_positions.bed",
		nearby_peaks = "{sample}/{sample}_nearby_peaks.tsv",
		segdup_intersect = "{sample}/{sample}_segdup_intersect.bed",
		max_depth = "{sample}/{sample}_max_depth_distance_to_boundary.txt",
		polyT_reads = "{sample}/{sample}_polyT_reads.txt",
		misalignment = "{sample}/{sample}_misalignment.txt"
	output:
		big_table = "{sample}/{sample}_big_table.tsv"
	benchmark:
		"benchmarks/run_big_table/{sample}.tsv"
	resources:
		runtime = get_create_big_table_runtime,
		mem_mb = get_create_big_table_mem_mb
	group: "classify"
	run:
		Ntag = pd.read_table(input.Ntag_list , sep="\t", header=None, names=["read","Ntag"])
		readIDs = pd.read_table(input.peak_readID_list, sep="\t", header=None, names=["peak_name","read"])
		readIDs = readIDs.merge(Ntag, how="left", on="read")
		del Ntag
		polyA = pd.read_table(input.polyT_reads, sep="\t",header=None, names=["read"])
		polyA["polyA"] = "pass_" + polyA['read']
		readIDs = readIDs.merge(polyA, how="left", on="read").fillna('fail')
		del polyA
		gmotif = pd.read_table(input.pass_gmotif_list, sep="\t", header=None, names=["read"])
		gmotif["gmotif"] = "pass_" + gmotif['read']
		readIDs = readIDs.merge(gmotif, how="left", on="read").fillna('fail')
		del gmotif
		readIDs = readIDs.fillna('')
		big_table = readIDs.groupby('peak_name').agg({'read': lambda x: len(list(set(x))),
													  'Ntag': lambda x: ([y for y in list(set(x)) if (len(y) == 2 or len(y) == 4 or len(y) == 6)]),
													  'polyA': lambda x: len(list(set([y for y in x if y != "fail"]))),
													  'gmotif': lambda x: len(list(set([y for y in x if y != "fail"])))}).reset_index()
		del readIDs
		peaks = pd.read_table(input.peaks, sep="\t", header=0)
		big_table = peaks.merge(big_table, how="left", on="peak_name")
		del peaks
		chimera = pd.read_table(input.chimera, sep="\t", header=None, names=["peak_name"])
		chimera['chimera'] = 'chimera'
		nonchimera = pd.read_table(input.nonchimera, sep="\t", header=None, names=["peak_name"])
		nonchimera['chimera'] = 'nonchimera'
		chimeras = pd.concat([chimera, nonchimera])
		misalignment = pd.read_table(input.misalignment, sep="\t", header=None, names=["peak_name"])
		misalignment['misalignment'] = 'misalignment'
		chimeras = chimeras.merge(misalignment, how="left", on=["peak_name"]).fillna("pass")
		big_table = big_table.merge(chimeras, how="left", on="peak_name")
		del chimera, chimeras, nonchimera, misalignment
		intersect = pd.read_table(input.intersect_annotated, sep="\t", header=0)
		big_table = big_table.merge(intersect[['peak_name','RepeatMasker','Evrony_KR','Homopolymers', 
											   '1000_Genomes_Project','gnomAD','NyuWa','xTea', 
											   'HGSVC3','HGSVC3-MELT-LRA','1019_ONT']], 
											   how="left", on="peak_name")
		del intersect  
		usp = pd.read_table(input.unique_start_positions, sep="\t", header=0)
		usp.columns = usp.columns.str.strip("#")
		big_table = big_table.merge(usp, how="left", on="peak_name")
		del usp
		big_table["RPM"] = (big_table['num_peak_reads'] / (big_table['num_bam_reads'])) * 1000000
		nearby_peak = pd.read_table(input.nearby_peaks, sep="\t", names=['nearest_peak','peak_name'])
		nearby_peak['peak_name'] = nearby_peak['peak_name'].str.split(pat="=")
		nearby_peak = nearby_peak.explode('peak_name')
		big_table = big_table.merge(nearby_peak, how="left", on="peak_name")
		del nearby_peak
		segdups = pd.read_table(input.segdup_intersect, sep="\t", names=['chr','start','end','peak_name','SegDup'])
		big_table = big_table.merge(segdups[['peak_name','SegDup']], how="left", on="peak_name")
		del segdups
		max_depth_distance = pd.read_table(input.max_depth,sep="\t", header=None, names=['peak_name','distance'] ) 
		big_table = big_table.merge(max_depth_distance, how="left", on="peak_name")
		del max_depth_distance 
		big_table = big_table.replace(r',{2,}', '', regex=True)

		big_table.to_csv(output.big_table, sep="\t", index=False, header=True, na_rep="")

rule filter_and_classify:
	input:
		big_table = "{sample}/{sample}_big_table.tsv",
	output:
		filter_reasons = "{sample}/{sample}_big_table_filter_reasons.tsv",
		classified_peaks = "{sample}/{sample}_classified_peaks.bed",
		plots = "{sample}/{sample}_filtering_plots.pdf",
		igv_script = "{sample}/{sample}_igv.sh",
		summary_file = "{sample}/{sample}_summary.txt"
	benchmark:
		"benchmarks/filter_and_classify/{sample}.tsv"
	params: 
		truth_set = lambda wildcards: samples.loc[wildcards.sample]["truth_set"], # optional 
		path = lambda wildcards: os.getcwd() + f"/{wildcards.sample}/igv/"
	conda:
		"envs/plotR.yml"
	resources: 
		runtime = get_min_runtime,
		mem_mb = get_filter_and_classify_mem_mb,
	group: "classify"
	shell:
		"Rscript {workflow.basedir}/scripts/filter_and_plot.R "
			"{input.big_table} {LIBRARY} {output.plots} {output.classified_peaks} {output.summary_file} "
			"{ERROR_PRONE} {params.truth_set} \n"
		"grep -E 'UNK|SOM' {output.classified_peaks} | "
			"awk -v OFS='\t' 'NR>1 {{print $1,$2,$3,$4}}' | "
			"bedtools igv -name -slop 200 -path {params.path} -i stdin "
			"> {output.igv_script}"

rule map_transduction_fasta:
	input:
		classified_peaks = "{sample}/{sample}_classified_peaks.bed",
		ref_genome = REF_GENOME,
		L1HS_decoy = L1HS_DECOY,
		softclip3p_fasta = "{sample}/{sample}_softclip_3p.fa.gz",
		softclip5p_fasta = "{sample}/{sample}_softclip_5p.fa.gz",
		hardclip3p_table = "{sample}/{sample}_hardclip_3p.tsv",
		hardclip5p_table = "{sample}/{sample}_hardclip_5p.tsv",
		#cutadapt_report = "{sample}/reports/{sample}_cutadapt_report.txt"
	output:
		transduction_bed =  "{sample}/{sample}_custom_transduction.bed",
		transduction_fasta = "{sample}/{sample}_custom_transduction.fasta",
		transduction_fasta_index = "{sample}/{sample}_custom_transduction.fasta.bwt",
		softclip3p_trimmed_fasta = "{sample}/{sample}_softclip_3p_trimmed.fa.gz",
		softclip5p_trimmed_fasta = "{sample}/{sample}_softclip_5p_trimmed.fa.gz",
		softclip3p_trimmed_bam = "{sample}/{sample}_softclip_3p_trimmed.bam",
		softclip5p_trimmed_bam = "{sample}/{sample}_softclip_5p_trimmed.bam",
		softclip3p_trimmed_bed = "{sample}/{sample}_softclip_3p_trimmed.bed",
		softclip5p_trimmed_bed = "{sample}/{sample}_softclip_5p_trimmed.bed",
		hardclip3p_bed = "{sample}/{sample}_hardclip_3p.bed",
		hardclip5p_bed = "{sample}/{sample}_hardclip_5p.bed",
		transduction_report = "{sample}/reports/{sample}_transduction_report.txt"
	benchmark:
		"benchmarks/map_transduction_fasta/{sample}.tsv"
	params:
		adapter_T = "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
		min_length = 10,
		RG_ID = lambda wildcards: fr"-R '@RG\tID:{TE_NAME}\tSM:{wildcards.sample}\tPL:{SEQ_PLATFORM}\tLB:HAT-seq\tCN:{SEQ_CENTER}'"
	threads: 4
	resources:
		runtime = get_map_transduction_fasta_runtime,
		mem_mb = get_map_transduction_fasta_mem_mb,
	group: "transduction"
	shell:
		"set -x \n"

		"awk -v OFS='\t' '{{if ($7 != \"FP\") print $1,$2,$3,$4}}' {input.classified_peaks} | "
			"sort -k1,1 -k2,2n | "
			"bedtools merge -i stdin -c 4 -o collapse | "
			"awk -v OFS='\t' '{{print $1,$2,$3,\"{wildcards.sample}_custom_reference_\"NR,$4}}' "
			"> {output.transduction_bed} \n"

		# Everything is with respect to the reference at this point, fasta of loci and fasta of softclipped reads
		"bedtools getfasta -fi {input.ref_genome} -bed {output.transduction_bed} -name > {output.transduction_fasta} \n" 
		
		"cat {input.L1HS_decoy} >> {output.transduction_fasta} \n" 
		"bwa index {output.transduction_fasta} \n"

		"cutadapt -g X{params.adapter_T} -m {params.min_length} "
			"-o {output.softclip3p_trimmed_fasta} "
			"{input.softclip3p_fasta} "
			">> {output.transduction_report} \n"
		"cutadapt -a {params.adapter_T}X -m {params.min_length} "
			"-o {output.softclip5p_trimmed_fasta} "
			"{input.softclip5p_fasta} "
			">> {output.transduction_report} \n"

		"bwa mem -t {threads} {params.RG_ID} {output.transduction_fasta} {output.softclip3p_trimmed_fasta} | "
			"samtools sort -o {output.softclip3p_trimmed_bam}  \n"
		"bwa mem -t {threads} {params.RG_ID} {output.transduction_fasta} {output.softclip5p_trimmed_fasta} | "
			"samtools sort -o {output.softclip5p_trimmed_bam} \n"
		"samtools index {output.softclip3p_trimmed_bam} \n"
		"samtools index {output.softclip5p_trimmed_bam} \n"
		"samtools view -q 20 {output.softclip3p_trimmed_bam} | "
			"awk '{{ for (i=1;i<=NF;i++) "
				"{{ if ($i ~/AS:i:/) "
					"{{split ($i,a,\":\")}}; "
				"if ($i ~/XS:i:/) "
					"{{split ($i,b,\":\")}} }}; "
				"if (a[3]>b[3]) print; }}' | "
			"awk '{{ for (i=1;i<=NF;i++) "
				"{{ if ($i ~/NM:i:/) "
					"{{split ($i,a,\":\"); "
				"if (a[3]<4) print; }} }} }}' | "
			"cat <(samtools view -H {output.softclip3p_trimmed_bam}) - | "
			"samtools view -Sb - | "
			"bamToBed -i stdin "
			"> {output.softclip3p_trimmed_bed} \n" 
		"samtools view -q 20 {output.softclip5p_trimmed_bam} | "
			"awk '{{ for (i=1;i<=NF;i++) "
				"{{ if ($i ~/AS:i:/) "
					"{{split ($i,a,\":\")}}; "
				"if ($i ~/XS:i:/) "
					"{{split ($i,b,\":\")}} }}; "
				"if (a[3]>b[3]) print; }}' | "
			"awk '{{ for (i=1;i<=NF;i++) "
				"{{ if ($i ~/NM:i:/) "
					"{{split ($i,a,\":\"); "
				"if (a[3]<4) print; }} }} }}' | "
			"cat <(samtools view -H {output.softclip5p_trimmed_bam}) - | "
			"samtools view -Sb - | "
			"bamToBed -i stdin > "
			"{output.softclip5p_trimmed_bed} \n"
		
		"bedtools intersect -wa -wb "
			"-a <(awk '{{OFS=\"\\t\"; split($2,a,\":\"); split(a[2],b,\"-\"); print a[1],b[1],b[2],$1,\".\",a[3]}}' {input.hardclip3p_table}) "
			"-b {output.transduction_bed} "
			"> {output.hardclip3p_bed} \n"
		"bedtools intersect -wa -wb "
			"-a <(awk '{{OFS=\"\\t\"; split($2,a,\":\"); split(a[2],b,\"-\"); print a[1],b[1],b[2],$1,\".\",a[3]}}' {input.hardclip5p_table}) "
			"-b {output.transduction_bed} "
			"> {output.hardclip5p_bed} \n"		

rule transduction_big_table: 
	input:
		peak_readID_list = "{sample}/{sample}_peak_readID_list.txt",
		hardclip3p_bed = "{sample}/{sample}_hardclip_3p.bed",
		hardclip5p_bed = "{sample}/{sample}_hardclip_5p.bed",
		softclip3p_trimmed_bed = "{sample}/{sample}_softclip_3p_trimmed.bed",
		softclip5p_trimmed_bed = "{sample}/{sample}_softclip_5p_trimmed.bed",
		transduction_bed =  "{sample}/{sample}_custom_transduction.bed",
	output:
		transduction_big_table = "{sample}/{sample}_transduction_big_table.tsv"
	benchmark:
		"benchmarks/run_transduction_big_table/{sample}.tsv"
	resources:
		runtime = get_transduction_big_table_runtime,
		mem_mb = get_transduction_big_table_mem_mb
	group: "transduction"
	run:
		readIDs = pd.read_table(input.peak_readID_list, sep="\t", header=None, names=["peak_name","read"])
		soft3p = pd.read_table(input.softclip3p_trimmed_bed, sep="\t", header=None, names=["3p_soft_clip","start_s3p","end_s3p","read","mapq_s3p","strand_s3p"])
		readIDs = readIDs.merge(soft3p[["read","3p_soft_clip"]], how="left", on="read")
		del soft3p 
		soft5p = pd.read_table(input.softclip5p_trimmed_bed, sep="\t", header=None, names=["5p_soft_clip","start_s5p","end_s5p","read","mapq_s5p","strand_s5p"])
		readIDs = readIDs.merge(soft5p[["read","5p_soft_clip"]], how="left", on="read")
		del soft5p 
		hard5p = pd.read_table(input.hardclip5p_bed, sep="\t", header=None, names=["chr","start","end","read","null","strand","chr_ref","start_ref","end_ref","5p_hard_clip","peaks"])
		readIDs = readIDs.merge(hard5p[["read","5p_hard_clip"]], how="left", on="read")
		del hard5p 
		hard3p = pd.read_table(input.hardclip3p_bed, sep="\t", header=None, names=["chr","start","end","read","null","strand","chr_ref","start_ref","end_ref","3p_hard_clip","peaks"])
		readIDs = readIDs.merge(hard3p[["read","3p_hard_clip"]], how="left", on="read")
		del hard3p 
		readIDs = readIDs.fillna('')
		big_table = readIDs.groupby('peak_name').agg({'read': lambda x: len(list(set(x))),
													  '3p_soft_clip': lambda x: ','.join(list(set(x))),
													  '5p_soft_clip': lambda x: ','.join(list(set(x))),
													  '5p_hard_clip': lambda x: ','.join(list(set(x))),
													  '3p_hard_clip': lambda x: ','.join(list(set(x)))}).reset_index()
		del readIDs
		custom_ref_peak = pd.read_table(input.transduction_bed, sep="\t", usecols=[3,4], names=["custom_ref_peak","peak_name"])
		custom_ref_peak["peak_name"] = custom_ref_peak["peak_name"].str.split(",")
		custom_ref_peak = custom_ref_peak.explode("peak_name")
		big_table = big_table.merge(custom_ref_peak, how="left", on="peak_name")
		del custom_ref_peak
		big_table = big_table.replace(r',{2,}', '', regex=True)
		big_table = big_table.replace(r'^,', '', regex=True)
		big_table.to_csv(output.transduction_big_table, sep="\t", index=False, header=True, na_rep="")

rule call_transductions: 
	input: 
		transduction_bed = "{sample}/{sample}_custom_transduction.bed", 
		transduction_big_table = "{sample}/{sample}_transduction_big_table.tsv", 
		classified_peaks = "{sample}/{sample}_classified_peaks.bed"
	output:
		transduction_plots = "{sample}/{sample}_transduction_plots.pdf",
		filtered_transduction = "{sample}/{sample}_filtered_transduction.tsv"
	benchmark:
		"benchmarks/call_transductions/{sample}.tsv"
	conda:
		"envs/plotR.yml"
	resources:
		runtime = get_min_runtime, 
		mem_mb = get_call_transductions_mem_mb,
	group: "transduction"
	shell:
		"Rscript {workflow.basedir}/scripts/transduction_calling.R "
			"{input.transduction_big_table} {output.transduction_plots} "
			"{output.filtered_transduction} {input.transduction_bed} {input.classified_peaks} \n"

rule multi_sample_classification:
	input:
		sample_peaks = lambda wildcards: expand("{name}/{name}_classified_peaks.bed", 
												  name=get_donor_samples(wildcards, samples))
	output:
		donor_peaks = "all_{donor}_candidate_peaks.bed",
		multi_peaks = "{donor}_multi_peaks.bed"
	benchmark:
		"benchmarks/multi_sample_classification/{donor}.tsv"
	params:
		num_samples = lambda wildcards, input: len(input.sample_peaks)
	resources:
		runtime = 10, #get_min_runtime,
		mem_mb = 4000 #get_filter_and_classify_mem_mb,
	group: "classify"
	shell:
		"if [[ {params.num_samples} -ge 3 ]]; then "
			"python {workflow.basedir}/scripts/multi_classify.py "
				"-d {wildcards.donor} "
				"-f {input.sample_peaks} "
				"-p {output.donor_peaks} "
				"-m {output.multi_peaks} \n"
		"else "
			"touch {output.multi_peaks} \n"
			"echo 'chrm\tstart\tend\tpeak\tRPM\tstrand\tclassification\tfilter_reason' "
				"> {output.donor_peaks} \n"
			"cat {input.sample_peaks} >> {output.donor_peaks} \n"
		"fi"	
		