#### Pipeline for calling L1HS insertions from HAT-seq libraries ####

# Import required libraries
import os
import pandas as pd
from snakemake.utils import validate, min_version

# Check version
min_version("7.32.0")

# Load rules
include: "rules/common.smk" # helper code
include: "rules/trim.smk"
include: "rules/align.smk"
include: "rules/seq_features.smk"
include: "rules/peaks.smk"
include: "rules/classify.smk"
include: "rules/transduction.smk"

# Read metadata - this is a global variable
samples = pd.read_csv(config["metadata"], sep="\t", dtype=str)

# Validate configuration
config_schema = os.path.join(
	os.path.dirname(workflow.basedir), "config", "schemas", "config.schema.yml")
sample_schema = os.path.join(
	os.path.dirname(workflow.basedir), "config", "schemas", "samples.schema.yml")

validate(config, config_schema)
validate(samples, sample_schema)

# Format metadata
set_sample_names(samples)
samples = samples.set_index("sample_name", drop=False)

# ref_dir = config["reference_dir"]

localrules: HATseq

rule HATseq:
	input:
		expand([
		"{sample}/{sample}_peak_sorted_bwa.bam",
		"{sample}/{sample}_Ntag_list.txt",
		"{sample}/{sample}_pass_gmotif_list.txt",
		"{sample}/{sample}_polyT_reads.txt",
		"{sample}/{sample}_peaks.bed",
		"{sample}/{sample}_unique_start_positions.bed",
		"{sample}/{sample}_intersect_annotated.bed",
		"{sample}/{sample}_big_table.tsv",
		"{sample}/{sample}_classified_peaks.bed",
		"{sample}/{sample}_custom_transduction.fasta",
		"{sample}/{sample}_transduction_plots.pdf",
		"{donor}_multi_peaks.bed"
		],
		sample=samples.index,
		donor=samples["donor"].unique())
