$schema: "https://json-schema.org/draft/2020-12/schema"
description: main configuration schema for the workflow
properties:
  metadata:
    type: string
    description: path to sample-sheet TSV file
  te_name:
    type: string
    default: "L1HS"
    description: name of TE being analyzed
  bwa_ref_genome:
    type: string
    description: path to reference genome
  reference_dir:
    type: string
    description: path to directory with annotation files
  error_prone:
    type: string
    description: path to .bed file of error-prone regions
  truth_set:
    type: string
    description: path to .bed file of true insertions
  library:
    type: string
    description: library type (bulk, single, microbulk)
    pattern: "bulk|single|micro"
  sequencing_platform:
    type: string
    description: sequencing platform used 
  adapter_sequence:
    type: string
    description: illumina adapter used, written 5' to 3'
    pattern: "^[ACGT]+$"

required:
  - metadata
  - te_name
  - bwa_ref_genome
  - reference_dir
  - library
  - sequencing_platform
  - illumina_adapter
