$schema: "https://json-schema.org/draft/2020-12/schema"
description: entries for the sample sheet
properties:
  donor:
    type: string
    description: donor name/identifier
  cell:
    type: string
    default: "-NA-"
    description: cell identifier (for single-cell)
  tissue:
    type: string
    default: "-NA-"
    description: tissue name
  raw_fastq1:
    type: string
    description: path to read 1
  raw_fastq2:
    type: string
    description: path to read 2
  index_seq:
    type: string
    description: 4 bp in-line index used during library prep 
  truth_set:
    type: string
    default: "-NA-"
    description: path to .bed file of true insertions

required:
  - donor
  - raw_fastq1
  - raw_fastq2
  - index_seq