samples: "/n/data1/bch/genetics/lee/rohini/HATseq-pipeline/config/samples.bulk.tsv"
te_name: "L1HS"
bwa_ref_genome: "/n/data1/bch/genetics/lee/reference/hg38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
reference_dir: "/n/data1/bch/genetics/lee/rohini/HATseq-pipeline/reference"
min_to_pass: "1"
num_cells: "1"
library: "bulk"
sequencing_platform: "NovaseqS4"
sequencing_center: "Psomagen"
