samples: "path/to/sample/sheet"
te_name: "TE_name"
bwa_ref_genome: "/path/to/reference/genome"
reference_dir: "/path/to/annotations"
min_to_pass: "1"
num_cells: "1"
library: "single|micro|bulk"
sequencing_platform: "name_of_sequencing_platform"
sequencing_center: "name_of_sequencing_center"
