metadata: "path/to/sample/sheet"
te_name: "TE_name"
bwa_ref_genome: "/path/to/reference/genome"
reference_dir: "/path/to/annotations"
library: "single|micro|bulk"
error_prone: "-NA-"
truth_set: "-NA-"
sequencing_platform: "name_of_sequencing_platform"
illumina_adapter: "adapter_sequence"
