name: HATseq
channels:
 - conda-forge
 - bioconda
 - free
dependencies:
 - python=3.7
 - bioconda::snakemake
 - conda-forge::numpy=1.21
 - pandas
 - bioconda::pysam
 - bioconda::samtools
 - bioconda::cutadapt
 - bioconda::bedtools=2.27.1
 - bioconda::pear
 - bioconda::samblaster
 - bioconda::pblat
 - bioconda::fastqc
 - bioconda::fastq-screen
 - bioconda::bowtie2
 - bioconda::sambamba
 - bioconda::bwa
 - bioconda::star=2.7.0d
 - bioconda::blast-legacy
